services:
  - type: web
    name: flowise-docker-render
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    repo: https://github.com/FlowiseAI/Flowise
    branch: main
    healthCheckPath: /health
    autoDeploy: false
    disk:
      name: flowise-disk
      mountPath: /opt/render/.flowise
      sizeGB: 1
 
  - name: chainlit
    type: web
    runtime: python
    buildCommand: pip install chainlit
    startCommand: chainlit hello
    repo: https://github.com/derekcheungsa/chainlit.git
    numInstances: 1

  
